title: "OCI Terraform  Configuration "
description: "Stack to deploy resources in OCI Tenancy"
stackDescription: "Stack to deploy resources in OCI Tenancy"
schemaVersion: 1.1.0
version: "20201125"
locale: "en"

variableGroups:
- title: "General Configuration"
  visible: false
  variables:
  - tenancy_ocid
  - user_ocid
  - fingerprint
  - private_key_path
  - region
  

- title: "Required Configuration"
  visible: true  
  variables:
  - customer_label
  - compartment_id
  - policies_in_root_compartment
  - show_advanced 
  
- title: "Networking  Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - ip_vcn
  - ip_sub_dmz
  - ip_sub_private
  - public_src_bastion_cidrs

- title: "VPN  Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - v1_cl_vpn
  - v1_cw_vpn
  - cust1_vpn
  - cust2_vpn
  - v1_cl_domain
  - v1_cw_domain
  - cust1_domain
  - cust2_domain
  - access
 

- title: "Database Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - data_storage_size_in_gb
  - db_shapes
  - db_shape_ocpus
  - ssh_key_db
  - db_shape_mem

- title: "Compute  Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - availablity_domain
  - shape_ocpus
  - shape_mem
  - backup_policy
  - boot_volume_size_in_gbs
  - instance_shape
  - ssh_key

- title: "Cloud Guard"
  variables:
    - cloud_guard_configuration_status
 
- title: "Vulnerability Scanning"
  variables:
    - vss_create
    - vss_scan_schedule
    - vss_scan_day

- title: "Events and Notifications"
  variables:
    - "network_admin_email_endpoints"

variables:

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false


  # General Configuration
  tenancy_ocid:
    title: "Tenancy ID"
    description: "The Oracle Cloud Identifier (OCID) for your tenancy"
    type: string
    required: true
    visibile: false

  region:
    title: "Region"
    description: "Choose Region where you deploy your application"
    type: oci:identity:region:name
    required: true
    visibile: true
  
  customer_label:
    title: "customer label"
    description: "Label used as a prefix for naming resources"
    type: string
    required: true
    visible: true

  compartment_id:
    title: "Compartment OCID"
    description: "Choose Comparment where you deploy your Webserver"
    type: oci:identity:compartment:id
    required: true
    visibile: true

  policies_in_root_compartment:
    type: enum
    title: "CREATE or USE policies in the root compartment?"
    description: "Whether policies in the root compartment should be created or simply used. If \"CREATE\", you must be sure the user executing this stack has permissions to create policies in the root compartment. If \"USE\", policies must have been created previously."
    enum:
      - "CREATE"
      - "USE"
    required: true
    default: "CREATE"
    visible: env_advanced_options
  

  # Network Configuration

  ip_vcn:
    type: string
    required: false
    default: "10.199.0.0/16"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR"
    description: "Choose single, contiguous IPv4 CIDR block for the VCN"
  

  ip_sub_dmz:
    type: string
    required: false
    default: "10.199.1.0/24"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Subnet IP - DMZ"
    description: "Choose single, contiguous IPv4 CIDR block for the Subnet"

  ip_sub_private:
    type: string
    required: false
    default: "10.199.2.0/24"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Subnet IP- PRIVATE"
    description: "Choose single, contiguous IPv4 CIDR block for the Subnet"

  public_src_bastion_cidrs:
    type: array
    items:
      type: string
    uniqueItems: true  
    title: "BASTION --Inbound SSH CIDR Blocks"
    #pattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"
    description: "List of external IP ranges in CIDR notation allowed to make SSH inbound connections. 0.0.0.0/0 is not allowed in the list. (Type the name and hit enter to enter multiple values)"
    default: []

# VPN Configuration

  v1_cl_vpn:
    type: string
    required: false
    default: "95.45.180.36"
    title: "CL VPN"
    description: "CL VPN"

  v1_cw_vpn:
    type: string
    required: false
    default: "159.134.94.228"
    title: "CW VPN"
    description: "CW VPN"

  cust1_vpn:
    type: string
    required: false
    default: "109.159.193.202"
    title: "cust1 vpn"
    description: "cust1 vpn

  cust2_vpn:
    type: string
    required: false
    default: "109.159.193.203"
    title: "cust2 vpn"
    description: "cust2 vpn"

  v1_cl_domain: 
    type: array
    items:
      type: string
    uniqueItems: true
    required: false
    maxItems: 9
    minItems: 1
    title: "CIDR Blocks for v1 vpns"
    description: "CIDR Blocks for v1 vpns"
    default: []


  v1_cw_domain: 
    type: array
    items:
      type: string
    uniqueItems: true
    required: false
    maxItems: 9
    minItems: 1
    title: "CIDR Blocks for customer vpns"
    description: "CIDR Blocks for customer vpns"
    default: []

  cust1_domain: 
    type: array
    items:
      type: string
    uniqueItems: true
    required: false
    maxItems: 9
    minItems: 1
    title: "CIDR Blocks for customer domain"
    description: "CIDR Blocks for customer domain"
    default: []


  cust2_domain:
    type: array
    items:
      type: string
    uniqueItems: true
    required: false
    maxItems: 9
    minItems: 1
    title: "v1_domains "
    description: "v1_domains"
    default: []

  access:
    type: array
    items:
      type: string
    uniqueItems: true
    required: false
    maxItems: 9
    minItems: 1
    title: "Access IPs "
    description: "Access IPs"
    default: []


# Compute Configuration
  
  availablity_domain:
    type: enum
    required: true
    visibile: true
    title: "Availability Domain to be chosen"
    description: "Choose Availability Domain where your application will be deployed."
    default: "3"
    enum:
      - "1"
      - "2"
      - "3"

  instance_shape:
    type: oci:core:instanceshape:name
    title: "Instance Shape"
    description: "Choose a shape for your instance"
    default: "VM.Standard.E2.1"
    required: false
    dependsOn:
      compartmentId: ${compartment_id}

  shape_ocpus:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 2
    title: "Shape OCPUs"
    description: "Choose number of OCPUs for Shape."

  shape_mem:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 16
    title: " Shape Memory (GB)"
    description: "Choose number GB for Shape Memory."

  backup_policy:
    type: enum
    required: false
    title: "backup policy"
    description: "choose backup policy for instances"
    default: "silver"
    enum:
      - "silver"
      - "bronze"
      - "gold"
  
  boot_volume_size_in_gbs:
    type: number
    required: false
    multipleOf: 1
    default: 100
    title: " Shape Memory (GB)"
    description: "Choose number GB for Shape Memory."

  ssh_key:
    title: SSH Public Key
    description: The public SSH key for the key-pair that you want to use, if you wish to login to the instances over SSH
    # renders variable as an SSH key control
    type: oci:core:ssh:publickey
    required: true

 # DB Configuration
  
  data_storage_size_in_gb:
    type: number
    required: false
    default: 100
    title: "Database storage size in GB"
    description: "Choose database storage size in GB for your DBSystem."

  db_shapes:
    type: oci:core:instanceshape:name
    title: "Instance Shape"
    description: "Choose a shape for your instance"
    default: "VM.Standard.E2.1"
    required: false
    dependsOn:
      compartmentId: ${compartment_id}


  ssh_key_db:
    title: SSH Public Key
    description: The public SSH key for the key-pair that you want to use, if you wish to login to the instances over SSH
    # renders variable as an SSH key control
    type: oci:core:ssh:publickey
    required: true

  db_shape_ocpus:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 2
    title: " Shape OCPUs"
    description: "Choose number of OCPUs for Shape."

  db_shape_mem:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 2
    title: "DB Shape Mem"
    description: "DB Shape Mem"


 # Cloud Guard
  
  cloud_guard_configuration_status:
    type: enum
    title: "Cloud Guard Configuration Status"
    description: "Determines whether Cloud Guard should be enabled in the tenancy. If 'ENABLE', a target is created for the Root compartment."
    required: true
    enum:
      - ENABLE
      - DISABLE

 # Vulnerability Scanning
  vss_create:
    type: boolean
    title: "Enable Vulnerability Scanning?"
    description: "Whether Vulnerability Scanning should be enabled. If checked, a scanning recipe is created and scanning targets are created for each Landing Zone compartment."
    default: true

  vss_scan_schedule:
    type: enum
    title: "Scanning Schedule"
    description: "When to scan. WEEKLY or DAILY."
    default: WEEKLY
    visible: vss_create
    enum:
      - WEEKLY
      - DAILY

  vss_scan_day:
    type: enum
    title: "Scanning Day"
    description: "The day when to scan. Applies to weekly scans only."
    default: SUNDAY
    enum:
      - SUNDAY
      - MONDAY
      - TUESDAY
      - WEDNESDAY
      - THURSDAY
      - FRIDAY
      - SATURDAY 
    visible:
      and:
        - ${vss_create}
        - eq:
          - vss_scan_schedule
          - WEEKLY

  
#Events and Notifications

  network_admin_email_endpoints:
    type: array
    items:
      type: string
    uniqueItems: true
    title: "Network Admin Email Endpoints"
    required: true
    description: "List of email addresses for all network related notifications. (Type an email address and hit enter to enter multiple values)"
