title: "OCI Terraform  Configuration "
description: "Stack to deploy resources in OCI Tenancy"
stackDescription: "Stack to deploy resources in OCI Tenancy"
schemaVersion: 1.1.0
version: "20201125"
locale: "en"

variableGroups:
- title: "General Configuration"
  visible: false
  variables:
  - tenancy_ocid
  - user_ocid
  - fingerprint
  - private_key_path
  - region
  

- title: "Required Configuration"
  visible: true  
  variables:
  - customer_label
  - compartment_id
  - show_advanced 
  
- title: "Networking  Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - ip_vcn
  - ip_sub_dmz
  - ip_sub_private

- title: "VPN  Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - v1_cl_domain
  - v1_cw_domain
  - cust1_domain
  - cust2_domain
  - access
 

- title: "Compute  Configuration(OPSVIEW Monitoring)"
  visible: 
      and:
        - show_advanced
  variables:
  - availablity_domain_opsview
  - shape_ocpus_opsview
  - shape_mem_opsview
  - backup_policy_opsview
  - boot_volume_size_in_gbs_opsview
  - instance_shape_opsview
  - instance_os
  - os_version_opsview
  - ssh_key_opsview

- title: "Compute  Configuration(Bastion)"
  visible: 
      and:
        - show_advanced
  variables:
  - instance_shape_bastion
  - shape_ocpus
  - shape_mem
  - boot_volume_size_in_gbs
  - instance_shape_bastion
  - os_version_bastion
  - ssh_key_bastion

variables:

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false


  # General Configuration
  tenancy_ocid:
    title: "Tenancy ID"
    description: "The Oracle Cloud Identifier (OCID) for your tenancy"
    type: string
    required: true
    visibile: false

  region:
    title: "Region"
    description: "Choose Region where you deploy your application"
    type: oci:identity:region:name
    required: true
    visibile: true
  
  customer_label:
    title: "customer label"
    description: "Label used as a prefix for naming resources"
    type: string
    required: true
    visible: true

  compartment_id:
    title: "Compartment OCID"
    description: "Choose Comparment where you deploy your Webserver"
    type: oci:identity:compartment:id
    required: true
    visibile: true

  

  # Network Configuration

  ip_vcn:
    type: string
    required: false
    default: "10.199.0.0/16"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR"
    description: "Choose single, contiguous IPv4 CIDR block for the VCN"
  

  ip_sub_dmz:
    type: string
    required: false
    default: "10.199.1.0/24"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Subnet IP - DMZ"
    description: "Choose single, contiguous IPv4 CIDR block for the Subnet"

  ip_sub_private:
    type: string
    required: false
    default: "10.199.2.0/24"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Subnet IP- PRIVATE"
    description: "Choose single, contiguous IPv4 CIDR block for the Subnet"



# VPN Configuration

  v1_cl_domain: 
    type: array
    items:
      type: string
    uniqueItems: true
    required: false
    maxItems: 9
    minItems: 1
    title: "V1 CL Domain"
    description: "V1 CL Domain"
    default: []


  v1_cw_domain: 
    type: array
    items:
      type: string
    uniqueItems: true
    required: false
    maxItems: 9
    minItems: 1
    title: "V1 CW Domain"
    description: "V1 CW Domain"
    default: []

  cust1_domain: 
    type: array
    items:
      type: string
    uniqueItems: true
    required: false
    maxItems: 9
    minItems: 1
    title: "CIDR Blocks for customer1 domain"
    description: "CIDR Blocks for customer1 domain"
    default: []


  cust2_domain:
    type: array
    items:
      type: string
    uniqueItems: true
    required: false
    maxItems: 9
    minItems: 1
    title: "CIDR Blocks for customer2 domain "
    description: "CIDR Blocks for customer2 domain"
    default: []

  access:
    type: array
    items:
      type: string
    uniqueItems: true
    required: false
    maxItems: 9
    minItems: 1
    title: "Access IPs "
    description: "Access IPs"
    default: []


# Compute Configuration
  
  availablity_domain:
    type: enum
    required: true
    visibile: true
    title: "Availability Domain to be chosen"
    description: "Choose Availability Domain where your application will be deployed."
    default: "2"
    enum:
      - "1"
      - "2"
      - "3"


  shape_ocpus:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 2
    title: "Shape OCPUs"
    description: "Choose number of OCPUs for Shape."

  shape_mem:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 16
    title: " Shape Memory (GB)"
    description: "Choose number GB for Shape Memory."

  backup_policy:
    type: enum
    required: false
    title: "backup policy"
    description: "choose backup policy for instances"
    default: "silver"
    enum:
      - "silver"
      - "bronze"
      - "gold"
  
  boot_volume_size_in_gbs:
    type: number
    required: false
    multipleOf: 1
    default: 100
    title: " Shape Memory (GB)"
    description: "Choose number GB for Shape Memory."



# Compute Configuration(OpsView)
  
  availablity_domain_opsview:
    type: enum
    required: true
    visibile: true
    title: "Availability Domain to be chosen"
    description: "Choose Availability Domain where your application will be deployed."
    default: "1"
    enum:
      - "1"
      - "2"
      - "3"

  instance_shape_opsview:
    type: oci:core:instanceshape:name
    title: "Instance Shape"
    description: "Choose a shape for your instance"
    default: "VM.Standard.E2.1"
    required: false
    dependsOn:
      compartmentId: ${compartment_id}

  shape_ocpus_opsview:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Shape OCPUs"
    description: "Choose number of OCPUs for Shape."

  shape_mem_opsview:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 8
    title: " Shape Memory (GB)"
    description: "Choose number GB for Shape Memory."

  backup_policy_opsview:
    type: enum
    required: false
    title: "backup policy"
    description: "choose backup policy for instances"
    default: "silver"
    enum:
      - "silver"
      - "bronze"
      - "gold"
  
  boot_volume_size_in_gbs_opsview:
    type: number
    required: false
    multipleOf: 1
    default: 100
    title: " Shape Memory (GB)"
    description: "Choose number GB for Shape Memory."

  ssh_key_opsview:
    title: SSH Public Key
    description: The public SSH key for the key-pair that you want to use, if you wish to login to the instances over SSH
    # renders variable as an SSH key control
    type: oci:core:ssh:publickey
    required: true

  instance_os_opsview:
    type: enum
    required: false
    visible: true
    title: "Instance OS"
    description: "Choose Operating System that determines the operating system for Webserver host."
    default: "Oracle Linux"
    enum:
      - "Oracle Linux"
      - "Windows Server"

  os_version_opsview:
    type: enum
    required: false
    visible: true
    title: "Instance OS version"
    description: "Choose Operating System version that determines the operating system version for Webserver host."
    default: "6.10"
    enum:
      - "7.9"  
      - "6.10"


#Bastion
  instance_shape_bastion:
    type: oci:core:instanceshape:name
    title: "Instance Shape"
    description: "Choose a shape for your instance"
    default: "VM.Standard.E2.1"
    required: false
    dependsOn:
      compartmentId: ${compartment_id}
  
  instance_os_bastion:
    type: enum
    required: false
    visible: true
    title: "Instance OS"
    description: "Choose Operating System that determines the operating system for Webserver host."
    default: "Oracle Linux"
    enum:
      - "Oracle Linux"
      - "Windows Server"

  os_version_bastion:
    type: enum
    required: false
    visible: true
    title: "Instance OS version"
    description: "Choose Operating System version that determines the operating system version for Webserver host."
    default: "7.9"
    enum:
      - "7.9"  
      - "6.10"
  
  ssh_key_bastion:
    title: SSH Public Key
    description: The public SSH key for the key-pair that you want to use, if you wish to login to the instances over SSH
    # renders variable as an SSH key control
    type: oci:core:ssh:publickey
    required: true

  
  

 